apiVersion: v2
name: monitoring
description: A overall chart for releases of all monitoring infrastructure

version: 0.1.0

dependencies:
  - name: collector
    version: 0.1.0
    repository: file://charts/collector
    condition: collector.enabled
  - name: grafana
    version: 0.1.0
    repository: file://charts/grafana
    condition: grafana.enabled