global:
  replicaCount: 1

  image:
    pullPolicy: IfNotPresent

  imagePullSecrets: [ ]

  serviceAccount:
    create: false
    automount: false
    annotations: { }

  podAnnotations: { }
  podLabels: { }

  podSecurityContext: { }

  securityContext: { }

  autoscaling:
    enabled: false

  nodeSelector: { }

  tolerations: [ ]

  affinity: { }

  serviceDiscoveryRoleBinding: true
  env:
    TEST_ENV: "TEST"

collector:
  enabled: true
  image:
    repository: "otel/opentelemetry-collector-contrib"
    tag: "0.105.0"
  pv:
    enabled: true
    accessModes:
      - ReadWriteMany
    hostPath: "/run/desktop/mnt/host/g/work/projects/mail-service/config/observability/otelcollector"
  pvc:
    enabled: true
    accessMode: ReadWriteMany
  volumeMounts:
    - name: config-volume
      mountPath: /etc/otelcol-contrib
  volumes:
    - name: config-volume
      persistentVolumeClaim:
        claimName: monitoring-collector-pvc
  service:
    ports:
      - port: 4317
        targetPort: 4317
        name: logs
        protocol: TCP
      - port: 8008
        targetPort: 8008
        name: monitoring
        protocol: TCP
      - port: 4318
        targetPort: 4318
        name: metrics
        protocol: TCP
      - port: 4319
        targetPort: 4319
        name: traces
        protocol: TCP
  ports:
    - name: logs
      containerPort: 4317
      protocol: TCP
    - name: metrics
      containerPort: 4318
      protocol: TCP
    - port: 8008
      containerPort: 8008
      name: monitoring
      protocol: TCP
    - name: traces
      containerPort: 4319
      protocol: TCP
  resources:
    requests:
      memory: 256Mi
      cpu: 20m
    limits:
      memory: 512Mi
      cpu: 300m
