apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-opensearch-cluster-pv-1
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1024Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/g/work/projects/deployment/config/observability/opensearch/pvc"