services:
  # grep 'Password:' /etc/gitlab/initial_root_password
  # root/password
  # don't forget to enabled https for host
  # setup gitlab runner in ui and config
  # setup sonarqube using pipeline with one of the projects
  gitlab:
    image: gitlab/gitlab-ce:17.3.3-ce.0
    restart: always
    hostname: 'gitlab.berte.com'
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost/-/readiness?all=1 || exit 1"
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 20s
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.berte.com'
        registry_external_url "http://registry.berte.com"
        pages_external_url "http://pages.berte.com/"
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        gitlab_rails['monitoring_whitelist'] = ['127.0.0.0/8', '::1/128']
        gitlab_rails['backup_keep_time'] = 604800
        letsencrypt['auto_renew'] = true
        gitlab_pages['inplace_chroot'] = true
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - gitlab_configs:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
  sonarqube:
    image: sonarqube:community
    depends_on:
      - sonar_db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    environment:
      TZ: UTC
    volumes:
      - ${DOCKER_SOCKET}:/var/run/docker.sock
      - gitlab-runner-config:/etc/gitlab-runner
      - ./config.toml:/etc/gitlab-runner/config.toml
  sonar_db:
    image: postgres:16.3
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    command: postgres -c shared_preload_libraries='pg_stat_statements'
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:
  gitlab_configs: { }
  gitlab_logs: { }
  gitlab_data: { }

  gitlab-runner-config: { }

  sonarqube_data: { }
  sonarqube_extensions: { }
  sonarqube_logs: { }

  postgresql: { }
  postgresql_data: { }
