apiVersion: v2
name: persistence
description: A overall chart for persistent infrastructure releases

version: 0.1.0

dependencies:
  - name: keydb
    version: 0.1.0
    repository: file://charts/keydb
    condition: keydb.enabled

  - name: zookeeper
    version: 0.1.0
    repository: file://charts/zookeeper
    condition: zookeeper.enabled

  - name: kafka-cluster
    version: 0.1.0
    repository: file://charts/kafka-cluster
    condition: kafka-cluster.enabled

  - name: clickhouse-cluster
    version: 0.1.0
    repository: file://charts/clickhouse-cluster
    condition: clickhouse-cluster.enabled

  - name: postgres-cluster
    version: 0.1.2
    repository: file://charts/postgres-cluster
    condition: postgres-cluster.enabled