apiVersion: v2
name: persistence
description: A overall chart for persistent infrastructure releases

version: 0.1.0

dependencies:
  - name: keydb
    version: 0.1.0
    repository: file://charts/keydb
    condition: keydb.enabled

  - name: kafka
    version: 0.1.0
    repository: file://charts/kafka
    condition: kafka.enabled

  - name: clickhouse
    version: 0.1.4
    repository: file://charts/clickhouse
    condition: clickhouse.enabled

  - name: postgres
    version: 0.1.2
    repository: file://charts/postgres
    condition: postgres.enabled
