apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Release.Name }}-kafka-cluster
  namespace: {{ .Release.Namespace }}
spec:
  kafka:
    version: {{ .Values.kafka.version }}
    replicas: {{ .Values.kafka.replicas }}
    listeners:
      - name: plain
        port: {{ .Values.kafka.listeners.plain.port }}
        type: {{ .Values.kafka.listeners.plain.type }}
        tls: {{ .Values.kafka.listeners.plain.tls }}
    storage:
      type: ephemeral
  zookeeper:
    replicas: {{ .Values.zookeeper.replicas }}
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
