concurrent = 5 # A global setting for job concurrency that applies to all runner sections defined in this `config.toml` file
log_level = "info"
log_format = "json"
check_interval = 5 # Value in seconds

[[runners]]
    name = "Main"
    url = "http://gitlab/"
    executor = "docker"
    token = "glrt-__pDZsae5VXo1X-Q2sUw"
    [runners.docker]
        tls_verify = false
        image = "docker:24.0.5"
        priviledged = true
        disable_cache = false
        volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache/gitlab"]
        pull_policy = "if-not-present"
        cache_dir = "/cache/gitlab"