apiVersion: v2
name: ui
description: A overall chart for ui releases

version: 0.1.0

dependencies:
  - name: grafana
    version: 0.1.0
    repository: file://charts/grafana
    condition: grafana.enabled