kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: {{ .Release.Name }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    team: {{ .Values.team }}

spec:
  teamId: {{ .Values.team }}

  postgresql:
    version: "{{ .Values.version }}"
  numberOfInstances: {{ .Values.replicas }}
  enableConnectionPooler: true
  enableReplicaConnectionPooler: true
  maintenanceWindows:
  volume:
    size: "256Mi"
    storageClass: "hostname"


  allowedSourceRanges:
  # IP ranges to access your cluster go here
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: 120m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi

