apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-postgres-cluster-pv-1
spec:
  storageClassName: hostname
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1024Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/g/work/projects/deployment/config/db/postgres/pvc"