apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Namespace }}.test.{{ .Release.Name }}-postgres.credentials.postgresql.acid.zalan.do
type: Opaque
data:
  password: YWRtaW4=
  username: YWRtaW4=