apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: {{ .Release.Name }}-clickhouse
  namespace: {{ .Release.Namespace }}
spec:
  configuration:
    clusters:
      - name: "cluster"
        layout:
          shardsCount: 2
          replicasCount: 2
        templates:
          podTemplate: clickhouse-default
        clusterServiceTemplate:
          spec:
            type: ClusterIP