apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: {{ .Release.Name }}-clickhouse
spec:
  configuration:
    clusters:
      - name: "cluster"
        layout:
          shardsCount: 2
          replicasCount: 2